### ISSUE TITLE
Setting up default speed option does not work

### ISSUE THREAD

**Issue by hashcodez123** [rudiedirkx/Vimeo-repeat#14]
The playback speed button gets highlighted, but stays at 1x when the default speed option is changed to something else.

**Comment by rudiedirkx** [comment]
Yeah, sometimes it does that. Vimeo resets the video `src` a few times, and that resets the speed, and Vimeo Repeat only sets the speed the first time. You're very welcome to improve it in a PR.

**Comment by andre-pedretti** [comment]
After suffering a little bit, I got the way the bug shows itself.
Extension enabled, speed set, webpage accessed with embedded Vimeo video. Set speed shown on screen but, when the mouse goes over the video, the 1x speed is set again.
Before any mouse movement:
![image](https://user-images.githubusercontent.com/29348672/101381033-02038600-3895-11eb-94fa-38bebf812b8a.png)
After mouse over on one of the videos on the same frame:
![image](https://user-images.githubusercontent.com/29348672/101381104-1ba4cd80-3895-11eb-8a7a-2a84ff3a59de.png)

Anyone else could reproduce this behavior.

**Comment by rudiedirkx** [comment]
Very odd. Vimeo changes the `video.src` on mouse over, and that resets the speed too. I've added more dubious hacks in ba00949 to counteract that. Version 1.12 is on the way.
