### ISSUE TITLE
Does not work in Chrome 49

### ISSUE THREAD

**Issue by sammarcus** [rudiedirkx/Vimeo-repeat#2]
Hi,

The extension does not seem to work on Chrome for OS X 49.0.2623.112 (64-bit). There are no additional buttons on the Vimeo player and clicking the extension opens the Chrome Web Store. Based on recent reviews it seems others are having similar issues, suggesting a change on Vimeo's end that may have broken this.

Thank you!

**Comment by rudiedirkx** [comment]
It works for me on Chrome 50 (stable) on Win. I see a REPEAT and a  SPEED button: http://screencast.com/t/KqnGn4olUYCP

If you open the DevTools (F12?), are there any errors from `vimeo.js` ?

Or are you watching an embedded video? If so, URL please, so I can debug there.

**Comment by sammarcus** [comment]
Thanks so much for the help! I reinstalled it and it works wonderfully now. Sorry for not troubleshooting more thoroughly prior to opening this.

I love this extension. Thank you, Rudie!

**Comment by rudiedirkx** [comment]
No problem. I don't use Vimeo much anymore, so when it does break, let me know.
