### ISSUE TITLE
2 entire menus per video?

### ISSUE THREAD

**Issue by dbonneville** [rudiedirkx/Vimeo-repeat#3]
http://prntscr.com/brmcch

I'm seeing 2 menus now on all my videos. It didn't use to look like this until the last week or so. I haven't uninstalled and reinstalled it or anything. Any ideas?

Here is the video where I got the above screenshot from:

http://www.realclearlife.com/2016/07/11/solar-powered-3d-printer-taps-energy-of-sahara-desert/

**Comment by rudiedirkx** [comment]
I'm getting that too. Do you have any more embedded Vimeo videos, for comparison?

I'm debugging. Thanks for reporting.

**Comment by dbonneville** [comment]
I have many behind a video course paywall. They all have it at the moment:

http://prntscr.com/bs37mr

=====
Douglas Bonneville
douglas@bonfx.com

**Comment by rudiedirkx** [comment]
That was weird. Debugging fixed it, and then it didn't, etc. I've built in a few safeguards, so it should always trigger once.

Since this is the only open issue, I'll create a new release soon.

**Comment by dbonneville** [comment]
Cool! Will the extension autoupdate on a new release?

Thanks,
Doug

=====
Douglas Bonneville
douglas@bonfx.com

**Comment by rudiedirkx** [comment]
Yes, it should, but that might take a few hours, maybe a day. Let me know if weird things keep happening.
