### ISSUE TITLE
Not working on Vimeo or Short of the Week

### ISSUE THREAD

**Issue by KurtOstergaard** [rudiedirkx/Vimeo-repeat#5]
I can not adjust the speed of videos at

http://www.shortoftheweek.com/ or
http://vimeo.com

I can see the button but nothing happens.

**Comment by rudiedirkx** [comment]
* shortoftheweek - buttons clash with their UI, so probably not usable
* vimeo - doesn't work for all videos, like semi-embeds, but should work for video pages

What does

> I can see the button but nothing happens.

mean exactly? Can you click the buttons? Hover them? See their tooltip? Mousewheel over the speed?

I don't see anything broken, so I'll need more info from you. Screenshots or screengrab video would be great.
