### ISSUE TITLE
Extension stopped working 

### ISSUE THREAD

**Issue by h8pathak** [rudiedirkx/Vimeo-repeat#6]
It was working fine till yesterday but today the icons have stopped appearing. What could be the cause for this?  I have tried re-enabling and reinstalling the extension, and even reinstalling the browser but in vain. [ I am using Windows 10 with Chrome Version 59.0.3071.109 ] P.S. My chrome was about to update. So not sure it stopped working after the update or before it.

**Comment by krzemian** [comment]
Same here, using Chromium 58.0.3029.110 (64-bit) + Vimeo repeat & speed 1.6.
Disabling other extensions/rebooting doesn't help. 
Available alternatives:
- Video Speed: Watch videos at 1.25x-2x speed https://chrome.google.com/webstore/detail/video-speed-watch-videos/ggclgdahipehfjihdifhckmgmkjklnic?hl=pl - doesn't seem to work on embedded Vimeo videos, though
- https://chrome.google.com/webstore/detail/video-speed/fnjmlegmhldjolpmcfjhooibnchlafgg?hl=pl Video Speed

**Comment by vivek1kerala7** [comment]
Same here. This extension was working perfect till yesterday, but stopped working today. I did try reinstalling the extension, browser and even did reset my laptop but all in vain ! (Vimeo repeat and speed 1.6)

**Comment by rudiedirkx** [comment]
Are these alternatives any good? If they are, I'll stop this one.

**Comment by will-l-h** [comment]
Video Speed is ok but not without issues.  I like yours more; does it look like it will be a difficult fix?

**Comment by nelsonmarcos** [comment]
@rudiedirkx Video Speed works but your extensions is better.

**Comment by rudiedirkx** [comment]
I've released a new version (`1.7`). Shouldn't take more than a few hours.

Fix was not difficult, but very hacky. I'm not sure what changed and why that broke it...   But this seems to fix it.

**Comment by rudiedirkx** [comment]
Thanks for reporting on Github! :+1:

**Comment by h8pathak** [comment]
Thanks for correcting the bug @rudiedirkx  👍
