### ISSUE TITLE
Vimeo-repeat button disappeared

### ISSUE THREAD

**Issue by abbiestaton** [rudiedirkx/Vimeo-repeat#9]
I've been using the speed up button for 2 years (embedded videos on Emedley) and all of a sudden today the buttons disappeared. I tried uninstalling the extension and reinstalling it and the buttons are still missing.

**Comment by Tobithy** [comment]
Same issue here. I love this thing and hope it's able to come back.

**Comment by rudiedirkx** [comment]
Vimeo have probably changed their markup again. Every time they do, I have to change the extension code. But not all Vimeo users get the same markup, so it's tricky to fix for everyone. I'll look into it soon.

**Comment by rudiedirkx** [comment]
Easy fix. New version should be up in a few hours.
